### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-css-sass-intro-8dVLYn#1]
@egillespie Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-css-sass-intro-8dVLYn/) and meets the following criteria:

- [x] All components in [this HTML](https://gist.github.com/egillespie/15433761e640077f93660b4555a3d88b) are styled using Sass
- [x] Use four colors from a [random color palette](https://coolors.co/) (just copy the hex values into your Sass file) and link to your palette in the HTML
- [x] Font sizes are all determined by one base font size variable, even in `input` and `textarea` elements
- [x] All text uses the same font family, even in `input` and `textarea` elements
- [x] Elements shaped like a box (`img`, `input[type="text"]`, `textarea`) have the same `border-radius`
- [x] At least one built-in Sass function is used to style a component
- [x] Variables are defined in their own Sass file
- [x] Sass files are saved in a `source` directory and CSS files are saved in a `compiled` directory
- [x] A source map for your component library is included in the project

**Comment by KatieMFritz** [comment]
Hi Madeline, great start to this! I like the angled border radius. :rainbow:

There's one requirement you're missing:

>  Variables are defined in their own Sass file

I'd also like to see you make two other small changes, just to make sure you're comfortable using Sass:
1. Add some border radius and maybe a background color to your buttons
2. Nest selectors in your Sass file in a way that makes sense (maybe you can nest button styles under input styles, or add `hover` styles for something). 

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by levinsonmm** [comment]
Alrighty I think I took care of those issues! Let me know if there's anything else!

**Comment by KatieMFritz** [comment]
Nice job! 👩‍🎨 

:shipit:
